### ISSUE TITLE
Source code license

### ISSUE THREAD

**Issue by hollow87** [DavidGoldman/GuiLib#1]
I couldn't help but notice the lack of a source code license for your code.  One can not legally use this code in their application without your explicit permission which is kind of counter productive on putting it on github.  So I request that you put a license of some kinda up.

**Comment by DavidGoldman** [comment]
The "mod" is available for users to download on the [minecraft forums](http://www.minecraftforum.net/topic/1909236-/). While you may use this mod/library to create your own mod, you are not (currently, at least) allowed to distribute this mod's files. I'll consider it though - it may just be time to open source it.
