### ISSUE TITLE
Distrubute the source code of GuiLib with your mod.

### ISSUE THREAD

**Issue by vpant** [DavidGoldman/GuiLib#5]
Hello,
I am trying to build the my mod which is using your library, but if I remove the source code from my project and try to add it to dependencies section in my build.gradle file when I run the game my gui doesnt seem to render. The game gets paused but the gui doesnt show up. Is it alright if I build my mod with your library's source code in it?

Thanks in advance for you answer.

**Comment by DavidGoldman** [comment]
You can, but it might be better to just release this (GuiLab) and your mod as two separates packages just in case others are also still using GuiLib. Otherwise, if everyone includes it in their mod, there will be a problem.

**Comment by vpant** [comment]
Oh I see. Actually the mod that I develop is an academic project, I got no intend publishing it so it will be ok. Thanks very much for your answer :)

**Comment by DavidGoldman** [comment]
No problem.
